### ISSUE TITLE
9 Patch - Right Indicator (Content Height Padding) on XXHDPI and XXXHDPI is in #010101 instead of #000000

### ISSUE THREAD

**Issue by taylorling** [romannurik/AndroidAssetStudio#196]
Just wanted to file this because we found this issue when the dev having issue importing them into AS for XX and XXX, and turns out the the right indicator line is in #010101 so AS is complaining missing border/wrong color.

**Comment by taylorling** [comment]
Hey Roman (it's been a while 👋 ) - no rush, just thought to file this so if someone having the same issue, they are aware of the issue, and make changes manually.

**Comment by romannurik** [comment]
I just pushed the change, but not sure if it'll fix it. In case it doesn't, mind sharing a set of repro steps (e.g. with an example source PNG file) so I can try to reproduce the problem?

**Comment by romannurik** [comment]
OK this *should* be fully fixed by a4ddd69d987fbbb24a5012418f07b019d611b136

**Comment by taylorling** [comment]
@romannurik Hey buddy, I just give it a try and I still have the same issue.

Here's the source file I used: https://www.dropbox.com/s/xzv60k57mxy53da/btn-blue.png?dl=0

And here's the output zip that I got: https://www.dropbox.com/s/18bgpj25mmjjgc2/btn_blue.9.zip?dl=0

What I did is simply auto stretch, trimming, setting content padding and optical bound, then export. You can see in xxxhdpi, the right indicator is in #010101.

**Comment by romannurik** [comment]
Hrmmmmm, ok. Will re-open and investigate when I get a chance.

**Comment by romannurik** [comment]
Hm, Photoshop is showing RGB 0,0,0 for the xxxhdpi right indicator (content padding). Did i mix something up?

**Comment by taylorling** [comment]
With my 9-patches? If I use Sketch eyedropper on the xxxhdpi asset, it shows me #010101 or RGB 1,1,1 (attached below). If you try to import this assets into AS, it will prompt you that there is a missing color, so it's like not #000000. 

To make sure I didn't see the wrong asset, I just run a fresh generation using the tool again, and it still give me the same result.

![screenshot 2019-01-24 at 10 10 25 am](https://user-images.githubusercontent.com/7766387/51649699-8827c380-1fc0-11e9-86a5-99fcabe9f989.png)

**Comment by taylorling** [comment]
I just tried it on Photoshop and it's indeed showing 0,0,0 and I think it's not correct - if you use the Mac's Digital Color Meter, you can see that it's not entirely 0,0,0 - strange.

**Comment by romannurik** [comment]
Whoa, super weird. I'll take a look and see if I can fix the problem in Sketch :)

**Comment by romannurik** [comment]
Finally reproduced the problem... so weird that Photoshop shows 0,0,0.

**Comment by romannurik** [comment]
OK, the problem is alpha=254, not alpha=255, hence why Photoshop shows 0,0,0. Looking into it

**Comment by romannurik** [comment]
Should be fixed now.
